language: java
jdk: oraclejdk8
before_install: mvn clean
install: mvn install -DskipTests=true
script: echo "test skip"
deploy:
  provider: releases
  api_key:
    secure: ldB71pWzCrMHjmsYSmX3nMBrKktrirYK5Swh/OZq7dhTVCqtywbenniRUfJ3VazgNWxYrkoBgt5OpyQPjRpi0G37bCYw+qHSnSpsYw4BSpULATZhrDQ8F43cNKv2dlJ8WnY0AtBBwsPkdmu0aJgL61fUBn/d4rtRc6/vLt/Z8M0=
  file: war/target/ROOT.war
  on:
    repo: jonieet/aipo-opensocial
